'use client'

import { useState } from 'react'
import AuthModal from '@/components/AuthModal'

const PAIN = [
  { n: '01', q: 'Practice is fake pressure.', a: "Rehearsing alone is nothing like presenting to 12 people staring at you. Your nervous system knows the difference — and so does your speech." },
  { n: '02', q: 'Feedback comes too late.', a: "Post-call notes don't stop you from saying 'um' 14 times in a 20-minute pitch. Real coaching happens in the moment." },
  { n: '03', q: "You don't hear what others hear.", a: "Most people have never listened to themselves present. Filler words, rushed pacing, and dead air become invisible habits." },
  { n: '04', q: 'Coaching is expensive.', a: "A good public speaking coach runs $100–300/hour. Communication quality shouldn't depend on wealth." },
]

const FEATURES = [
  { icon: '🎙', title: 'Live transcription', desc: 'Deepgram-powered streaming transcript with sub-300ms latency. Every word, instantly.' },
  { icon: '⚠️', title: 'Filler detection', desc: 'Highlights um, uh, like, you know the moment they happen. Zero delay.' },
  { icon: '⏱', title: 'Pace meter', desc: 'Live words-per-minute with visual indicator. Green means good, red means slow down.' },
  { icon: '🤖', title: 'AI breakdown', desc: 'Post-session report generated by Claude. Timestamped moments, patterns, action items.' },
  { icon: '📉', title: 'Trend tracking', desc: 'Clarity score history across all sessions. See the week-over-week improvement.' },
  { icon: '🔒', title: 'Private by default', desc: 'Audio processed in real time, never stored. Transcript stays local. Your calls stay yours.' },
]

const TESTIMONIALS = [
  { quote: "I had no idea I was saying 'um' that much. Three weeks in and my filler count is down 60%. Genuinely changed how I present.", name: 'Sarah K.', role: 'Head of Product · Series B startup', avatar: '👩' },
  { quote: "The overlay is invisible to my clients but the feedback is right there. It's like having a coach whispering in your ear mid-pitch.", name: 'Marcus T.', role: 'Account Executive · Enterprise SaaS', avatar: '👨' },
  { quote: "Used to dread presenting. Now I actually look forward to my post-call breakdown. The clarity score gamifies the whole thing.", name: 'Priya M.', role: 'MBA student · Columbia Business', avatar: '🧑' },
]

const PLANS = [
  { name: 'Free', price: '0', features: ['3 sessions/month', 'Live WPM + filler tracking', 'Real-time coaching tips', 'Post-session grade & recap', 'Session history (last 10)'], cta: 'Download free', featured: false },
  { name: 'Pro', price: '14', features: ['Unlimited sessions', 'Live teleprompter', 'Full session history + trends', 'AI post-session breakdown', 'Priority support', 'Everything in Free'], cta: 'Start Pro — $14/mo', featured: true },
  { name: 'Team', price: '39', features: ['Up to 5 seats', 'Everything in Pro', 'Team analytics dashboard', 'Admin seat management', 'Slack weekly digest'], cta: 'Start Team plan', featured: false },
]

const mono = { fontFamily: 'var(--font-dm-mono)' } as const
const syne = { fontFamily: 'var(--font-syne)', fontWeight: 800 } as const
const tag  = { ...mono, fontSize: 10.5, color: 'var(--accent)', letterSpacing: '0.12em', textTransform: 'uppercase' as const, marginBottom: 16 }

export default function Landing() {
  const [showAuth, setShowAuth] = useState(false)

  return (
    <main style={{ background: 'var(--bg)', color: 'var(--text)', minHeight: '100vh' }}>

      {/* NAV */}
      <nav style={{ position: 'fixed', top: 0, left: 0, right: 0, zIndex: 200, height: 60, display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 40px', borderBottom: '1px solid var(--border)', background: 'rgba(9,9,11,.75)', backdropFilter: 'blur(24px)' }}>
        <div style={{ ...syne, fontSize: 17, letterSpacing: '-0.03em', display: 'flex', alignItems: 'center', gap: 7 }}>
          <div style={{ width: 7, height: 7, background: 'var(--accent)', borderRadius: '50%', animation: 'pulse 2s ease-in-out infinite' }} />
          SpeakUp
        </div>
        <div style={{ display: 'flex' }}>
          {['Features', 'Pricing', 'About'].map(l => (
            <a key={l} href={`#${l.toLowerCase()}`} style={{ color: 'var(--text2)', textDecoration: 'none', fontSize: 13.5, padding: '6px 14px', borderRadius: 6 }}>{l}</a>
          ))}
        </div>
        <div style={{ display: 'flex', gap: 10 }}>
          <button onClick={() => setShowAuth(true)} style={{ padding: '7px 16px', borderRadius: 7, fontSize: 13, fontWeight: 500, cursor: 'pointer', background: 'transparent', color: 'var(--text2)', border: '1px solid var(--border)', fontFamily: 'var(--font-dm-sans)' }}>Sign in</button>
          <button onClick={() => setShowAuth(true)} style={{ padding: '7px 16px', borderRadius: 7, fontSize: 13, fontWeight: 500, cursor: 'pointer', background: 'var(--accent)', color: '#09090b', border: 'none', fontFamily: 'var(--font-dm-sans)' }}>Get started</button>
        </div>
      </nav>

      {/* HERO */}
      <section style={{ minHeight: 'calc(100vh - 60px)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', padding: '120px 40px 60px', position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', top: '10%', left: '50%', transform: 'translateX(-50%)', width: 700, height: 500, background: 'radial-gradient(ellipse,rgba(34,197,94,0.05) 0%,transparent 68%)', pointerEvents: 'none' }} />

        <div style={{ display: 'inline-flex', alignItems: 'center', gap: 7, border: '1px solid var(--border)', borderRadius: 100, padding: '5px 14px 5px 8px', ...mono, fontSize: 10.5, color: 'var(--muted)', letterSpacing: '0.05em', marginBottom: 36, animation: 'fadeUp .6s ease both' }}>
          <div style={{ width: 5, height: 5, background: 'var(--accent)', borderRadius: '50%' }} />
          Floating overlay · Real calls · Mac
        </div>

        <h1 style={{ ...syne, fontSize: 'clamp(54px,9vw,104px)', letterSpacing: '-0.05em', lineHeight: 0.92, marginBottom: 24, animation: 'fadeUp .6s .1s ease both', maxWidth: 860 }}>
          Your AI coach<br />in <span style={{ color: 'var(--accent)' }}>every call.</span>
        </h1>

        <p style={{ fontSize: 17, color: 'var(--text2)', maxWidth: 460, lineHeight: 1.75, marginBottom: 44, animation: 'fadeUp .6s .2s ease both', fontWeight: 300 }}>
          SpeakUp sits invisibly on top of Zoom, Meet, and Teams — catching filler words, tracking pace, and coaching you in real time.
        </p>

        <div style={{ display: 'flex', gap: 14, animation: 'fadeUp .6s .3s ease both' }}>
          <button onClick={() => setShowAuth(true)} style={{ padding: '13px 26px', borderRadius: 9, fontSize: 14, fontWeight: 500, cursor: 'pointer', background: 'var(--accent)', color: '#09090b', border: 'none', fontFamily: 'var(--font-dm-sans)' }}>
            Download for Mac — Free
          </button>
          <a href="#features" style={{ padding: '13px 26px', borderRadius: 9, fontSize: 14, fontWeight: 500, cursor: 'pointer', background: 'transparent', color: 'var(--text2)', border: '1px solid var(--border)', textDecoration: 'none', fontFamily: 'var(--font-dm-sans)' }}>
            See how it works →
          </a>
        </div>

        {/* Demo window */}
        <div style={{ width: '100%', maxWidth: 800, marginTop: 72, animation: 'fadeUp .8s .45s ease both' }}>
          <div style={{ border: '1px solid var(--border)', borderRadius: 14, overflow: 'hidden', background: 'var(--surface)', boxShadow: '0 40px 120px rgba(0,0,0,.6)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '13px 18px', borderBottom: '1px solid var(--border)', background: 'rgba(255,255,255,.02)' }}>
              {['#ff5f57','#febc2e','#28c840'].map(c => <div key={c} style={{ width: 10, height: 10, borderRadius: '50%', background: c }} />)}
              <div style={{ margin: '0 auto', display: 'flex', alignItems: 'center', gap: 8 }}>
                <div style={{ width: 18, height: 18, background: 'var(--accent)', borderRadius: 5, display: 'flex', alignItems: 'center', justifyContent: 'center', ...mono, fontSize: 10, fontWeight: 700, color: '#09090b' }}>S</div>
                <span style={{ ...mono, fontSize: 11, letterSpacing: '0.04em' }}>SPEAKUP</span>
                <div style={{ width: 6, height: 6, background: 'var(--accent)', borderRadius: '50%', animation: 'pulse 2s ease-in-out infinite' }} />
                <span style={{ ...mono, fontSize: 11, color: 'var(--text2)' }}>00:07</span>
                <span style={{ background: 'var(--red)', color: '#fff', ...mono, fontSize: 9, fontWeight: 700, padding: '3px 8px', borderRadius: 5 }}>END</span>
              </div>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 260px' }}>
              <div style={{ padding: 28, borderRight: '1px solid var(--border)' }}>
                <div style={{ ...mono, fontSize: 9.5, color: 'var(--muted)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 14 }}>Live transcript</div>
                <div style={{ fontSize: 14.5, lineHeight: 1.85, color: 'var(--muted)', opacity: 0, animation: 'fadeUp .3s .8s ease forwards' }}>&ldquo;Good morning, thanks for joining today&apos;s call...&rdquo;</div>
                <div style={{ fontSize: 14.5, lineHeight: 1.85, color: 'var(--text)', opacity: 0, animation: 'fadeUp .3s 1.5s ease forwards' }}>&ldquo;I want to walk you through our Q3 performance&rdquo;</div>
                <div style={{ fontSize: 14.5, lineHeight: 1.85, color: 'var(--text)', opacity: 0, animation: 'fadeUp .3s 2.4s ease forwards' }}>
                  &ldquo;<span style={{ color: 'var(--red)', textDecoration: 'underline wavy', textUnderlineOffset: 3 }}>um</span> the numbers have been, <span style={{ color: 'var(--red)', textDecoration: 'underline wavy', textUnderlineOffset: 3 }}>like</span>, really strong&rdquo;
                </div>
                <div style={{ fontSize: 14.5, lineHeight: 1.85, color: 'var(--text)', opacity: 0, animation: 'fadeUp .3s 3.4s ease forwards' }}>
                  &ldquo;Revenue grew 40% year over year<span style={{ display: 'inline-block', width: 2, height: 15, background: 'var(--accent)', marginLeft: 2, animation: 'blink 1s step-end infinite', verticalAlign: 'middle' }} />&rdquo;
                </div>
              </div>
              <div style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 10 }}>
                {[
                  { label: 'Pace', val: '148', sub: 'wpm · ideal 120–150', color: 'var(--orange)', bar: true },
                  { label: 'Fillers this session', val: '7', sub: 'um ×4, like ×3', color: 'var(--red)', bar: false },
                  { label: 'Clarity score', val: '84', sub: '↑ 12 from last session', color: 'var(--accent)', bar: false },
                ].map(m => (
                  <div key={m.label} style={{ border: '1px solid var(--border)', borderRadius: 9, padding: 14, background: 'rgba(255,255,255,.018)' }}>
                    <div style={{ ...mono, fontSize: 9, color: 'var(--muted)', letterSpacing: '0.07em', textTransform: 'uppercase', marginBottom: 5 }}>{m.label}</div>
                    <div style={{ ...syne, fontSize: 26, letterSpacing: '-0.04em', lineHeight: 1, color: m.color }}>{m.val}</div>
                    <div style={{ fontSize: 10.5, color: 'var(--muted)', marginTop: 3 }}>{m.sub}</div>
                    {m.bar && <div style={{ height: 2.5, background: 'rgba(255,255,255,.06)', borderRadius: 2, marginTop: 9, overflow: 'hidden' }}><div style={{ height: '100%', background: 'var(--accent)', width: 0, borderRadius: 2, animation: 'fillbar 2s 1.8s ease forwards' }} /></div>}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* STATS */}
      <div style={{ padding: '48px 0', borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)' }}>
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 0 }}>
          {[['sub-300ms','Feedback latency'],['Real calls','Not simulations'],['85%+','Gross margin'],['Mac native','Electron overlay']].map(([n,l], i, arr) => (
            <div key={n} style={{ display: 'flex', alignItems: 'center' }}>
              <div style={{ textAlign: 'center', padding: '0 40px' }}>
                <div style={{ ...syne, fontSize: 36, letterSpacing: '-0.04em' }}>{n}</div>
                <div style={{ fontSize: 12, color: 'var(--muted)', marginTop: 3, letterSpacing: '0.02em' }}>{l}</div>
              </div>
              {i < arr.length - 1 && <div style={{ width: 1, height: 40, background: 'var(--border)' }} />}
            </div>
          ))}
        </div>
      </div>

      {/* PAIN */}
      <section style={{ padding: '100px 40px', maxWidth: 1080, margin: '0 auto' }}>
        <div style={tag}>The problem</div>
        <h2 style={{ ...syne, fontSize: 'clamp(36px,5vw,56px)', letterSpacing: '-0.04em', lineHeight: 0.97, marginBottom: 56, maxWidth: 520 }}>Why practice tools don&apos;t actually work</h2>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1, background: 'var(--border)', border: '1px solid var(--border)', borderRadius: 16, overflow: 'hidden' }}>
          {PAIN.map(p => (
            <div key={p.n} style={{ background: 'var(--bg)', padding: '40px 36px' }}>
              <div style={{ ...mono, fontSize: 11, color: 'var(--muted)', letterSpacing: '0.06em', marginBottom: 16 }}>{p.n}</div>
              <div style={{ ...syne, fontSize: 20, letterSpacing: '-0.025em', lineHeight: 1.25, marginBottom: 10 }}>{p.q}</div>
              <div style={{ fontSize: 14, color: 'var(--text2)', lineHeight: 1.7 }}>{p.a}</div>
            </div>
          ))}
        </div>
      </section>

      {/* FEATURES */}
      <section id="features" style={{ padding: '100px 40px', maxWidth: 1080, margin: '0 auto' }}>
        <div style={tag}>Features</div>
        <h2 style={{ ...syne, fontSize: 'clamp(36px,5vw,52px)', letterSpacing: '-0.04em', lineHeight: 0.97, marginBottom: 56, maxWidth: 480 }}>Everything in one overlay</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 1, background: 'var(--border)', border: '1px solid var(--border)', borderRadius: 16, overflow: 'hidden' }}>
          {FEATURES.map(f => (
            <div key={f.title} style={{ background: 'var(--bg)', padding: '34px 28px' }}>
              <div style={{ width: 38, height: 38, border: '1px solid var(--border)', borderRadius: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 18, fontSize: 17 }}>{f.icon}</div>
              <div style={{ ...syne, fontSize: 15.5, letterSpacing: '-0.025em', marginBottom: 8 }}>{f.title}</div>
              <div style={{ fontSize: 13, color: 'var(--text2)', lineHeight: 1.7 }}>{f.desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* TESTIMONIALS */}
      <section style={{ padding: '100px 40px', maxWidth: 1080, margin: '0 auto' }}>
        <div style={tag}>Early users</div>
        <h2 style={{ ...syne, fontSize: 'clamp(34px,5vw,50px)', letterSpacing: '-0.04em', lineHeight: 0.97, marginBottom: 56 }}>What people are saying</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 16 }}>
          {TESTIMONIALS.map(t => (
            <div key={t.name} style={{ border: '1px solid var(--border)', borderRadius: 14, padding: 28, background: 'var(--surface)' }}>
              <p style={{ fontSize: 14.5, lineHeight: 1.75, color: 'var(--text2)', marginBottom: 20 }}>&ldquo;{t.quote}&rdquo;</p>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <div style={{ width: 32, height: 32, borderRadius: '50%', background: 'var(--surface2)', border: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13 }}>{t.avatar}</div>
                <div>
                  <div style={{ fontSize: 13, fontWeight: 500 }}>{t.name}</div>
                  <div style={{ ...mono, fontSize: 11.5, color: 'var(--muted)' }}>{t.role}</div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" style={{ padding: '100px 40px 80px', maxWidth: 1080, margin: '0 auto' }}>
        <div style={{ ...tag, textAlign: 'center' }}>Pricing</div>
        <h2 style={{ ...syne, fontSize: 'clamp(44px,7vw,80px)', letterSpacing: '-0.05em', lineHeight: 0.95, textAlign: 'center', marginBottom: 16 }}>Simple pricing</h2>
        <p style={{ textAlign: 'center', fontSize: 16, color: 'var(--text2)', marginBottom: 52 }}>Start free. Upgrade when you&apos;re ready.</p>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 16, maxWidth: 960, margin: '0 auto' }}>
          {PLANS.map(plan => (
            <div key={plan.name} style={{ border: `1px solid ${plan.featured ? 'rgba(34,197,94,.25)' : 'var(--border)'}`, borderRadius: 16, padding: 36, background: plan.featured ? 'var(--surface2)' : 'var(--surface)', position: 'relative', overflow: 'hidden' }}>
              {plan.featured && <><div style={{ position: 'absolute', top: 0, left: '50%', transform: 'translateX(-50%)', width: 180, height: 1, background: 'linear-gradient(90deg,transparent,rgba(34,197,94,.6),transparent)' }} /><div style={{ position: 'absolute', top: 20, right: 20, background: 'var(--accent)', color: '#09090b', ...mono, fontSize: 9, letterSpacing: '0.08em', textTransform: 'uppercase', padding: '3px 10px', borderRadius: 100 }}>Popular</div></>}
              <div style={{ ...mono, fontSize: 10.5, color: 'var(--muted)', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 12 }}>{plan.name}</div>
              <div style={{ ...syne, letterSpacing: '-0.05em', lineHeight: 1, marginBottom: 4 }}>
                <sup style={{ fontSize: 20, verticalAlign: 'super', fontWeight: 600 }}>$</sup>
                <span style={{ fontSize: 48 }}>{plan.price}</span>
              </div>
              <div style={{ ...mono, fontSize: 12, color: 'var(--muted)', marginBottom: 28 }}>/month</div>
              <div style={{ height: 1, background: 'var(--border)', marginBottom: 24 }} />
              <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 11, marginBottom: 32, padding: 0 }}>
                {plan.features.map(f => (
                  <li key={f} style={{ fontSize: 13.5, color: 'var(--text2)', display: 'flex', alignItems: 'flex-start', gap: 10 }}>
                    <span style={{ color: 'var(--accent)', fontSize: 12, fontWeight: 700, flexShrink: 0, marginTop: 1 }}>✓</span>{f}
                  </li>
                ))}
              </ul>
              <button onClick={() => setShowAuth(true)} style={{ width: '100%', padding: 13, borderRadius: 9, fontFamily: 'var(--font-dm-sans)', fontSize: 14, fontWeight: 500, cursor: 'pointer', border: plan.featured ? 'none' : '1px solid var(--border)', background: plan.featured ? 'var(--accent)' : 'transparent', color: plan.featured ? '#09090b' : 'var(--text2)' }}>
                {plan.cta}
              </button>
            </div>
          ))}
        </div>
      </section>

      {/* FOOTER */}
      <footer style={{ padding: '48px 40px 32px', borderTop: '1px solid var(--border)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', maxWidth: 1080, margin: '0 auto' }}>
          <div style={{ ...syne, fontSize: 17, letterSpacing: '-0.03em', display: 'flex', alignItems: 'center', gap: 7 }}>
            <div style={{ width: 7, height: 7, background: 'var(--accent)', borderRadius: '50%', animation: 'pulse 2s ease-in-out infinite' }} />
            SpeakUp
          </div>
          <div style={{ ...mono, fontSize: 11, color: 'var(--muted)', letterSpacing: '0.03em' }}>
            © {new Date().getFullYear()} SpeakUp · All rights reserved.
          </div>
        </div>
      </footer>

      {showAuth && <AuthModal onClose={() => setShowAuth(false)} />}
    </main>
  )
}
