'use client'

const mono = { fontFamily: 'var(--font-dm-mono)' } as const

type Props = {
  session: {
    session_type: string
    goal?: string
    grade?: string
    duration_sec: number
    wpm_avg?: number
    confidence?: number
    filler_count?: number
    filler_map?: Record<string, number>
    word_count?: number
    tip_history?: string[]
    ai_coaching?: {
      summary: string
      strength: { observation: string; quote: string }
      improvement: { observation: string; quote: string }
      drill: string
    }
    created_at: string
  }
}

function fmt(sec: number) {
  return `${Math.floor(sec / 60)}m ${String(sec % 60).padStart(2, '0')}s`
}

export default function ExportSessionButton({ session: s }: Props) {
  function download() {
    const lines: string[] = [
      '═══════════════════════════════════════',
      `  SPEAKUP SESSION REPORT`,
      '═══════════════════════════════════════',
      '',
      `Date:       ${new Date(s.created_at).toLocaleString()}`,
      `Type:       ${s.session_type}`,
      s.goal ? `Goal:       ${s.goal}` : '',
      `Grade:      ${s.grade ?? '—'}`,
      `Duration:   ${fmt(s.duration_sec)}`,
      `Words:      ${s.word_count ?? 0}`,
      '',
      '── METRICS ────────────────────────────',
      `Avg WPM:    ${s.wpm_avg?.toFixed(0) ?? '—'}`,
      `Confidence: ${s.confidence?.toFixed(0) ?? '—'}`,
      `Fillers:    ${s.filler_count ?? 0}`,
      '',
    ]

    if (s.filler_map && Object.keys(s.filler_map).length > 0) {
      lines.push('── FILLER BREAKDOWN ───────────────────')
      Object.entries(s.filler_map)
        .sort((a, b) => b[1] - a[1])
        .forEach(([word, count]) => lines.push(`  "${word}": ${count}x`))
      lines.push('')
    }

    if (s.ai_coaching) {
      const c = s.ai_coaching
      lines.push('── AI COACHING REPORT ─────────────────')
      lines.push('')
      lines.push(c.summary)
      lines.push('')
      lines.push('STRENGTH')
      lines.push(c.strength.observation)
      lines.push(`  "${c.strength.quote}"`)
      lines.push('')
      lines.push('IMPROVE')
      lines.push(c.improvement.observation)
      lines.push(`  "${c.improvement.quote}"`)
      lines.push('')
      lines.push('DAILY DRILL')
      lines.push(c.drill)
      lines.push('')
    }

    if (s.tip_history && s.tip_history.length > 0) {
      lines.push('── COACHING TIPS SHOWN ────────────────')
      s.tip_history.forEach((tip, i) => lines.push(`  ${i + 1}. ${tip}`))
      lines.push('')
    }

    lines.push('═══════════════════════════════════════')
    lines.push('Generated by SpeakUp · speakup.ai')

    const text = lines.filter(l => l !== null).join('\n')
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `speakup-${s.session_type.toLowerCase().replace(/\s+/g, '-')}-${new Date(s.created_at).toISOString().slice(0, 10)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <button
      onClick={download}
      style={{
        ...mono, fontSize: 11, padding: '7px 16px', borderRadius: 8, cursor: 'pointer',
        border: '1px solid var(--border)', background: 'var(--surface)',
        color: 'var(--text2)', letterSpacing: '0.04em',
      }}
    >
      EXPORT
    </button>
  )
}
